# Generated by Django 4.2.7 on 2026-03-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotel_image_url',
            field=models.URLField(default='https://picsum.photos/400/300?random=999', max_length=500),
        ),
        migrations.AddField(
            model_name='room',
            name='room_image_url',
            field=models.URLField(default='https://picsum.photos/400/300?random=998', max_length=500),
        ),
    ]
