# Generated by Django 4.2.7 on 2026-03-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_image_remove_room_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='hotel_image_url',
            field=models.URLField(default='https://picsum.photos/400/300', max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_image_url',
            field=models.URLField(default='https://picsum.photos/400/300', max_length=500),
        ),
    ]
